### ISSUE TITLE
Add reference system markdown reports

### ISSUE THREAD

**Issue by carlossvg** [ros-realtime/ros2_realtime_benchmarks#9]
@flynneva 

I added the markdown reports for the reference system. However, there is something wrong when it's rendered with mkdocs (see https://ros-realtime.github.io/ros2_realtime_benchmarks/benchmark_results/galactic/reference_system/rpi4_rt/memory_and_cpu_usage_summary_report_120s.html). Do you know if have to configure anything else?

**Comment by flynneva** [comment]
@carlossvg yes! It's in the template I still need to fix it.

The script tags in the markdown for some reason have a tab or spaces before them. Just remove that and I'm the markdown should render the <script> tag as html.

**Comment by carlossvg** [comment]
@flynneva Thanks! I fixed the report: https://ros-realtime.github.io/ros2_realtime_benchmarks/benchmark_results/galactic/reference_system/rpi4_rt/executor_kpi_summary_report_120s.html

Btw, the results for the prioritized version looks pretty good
